In [6]:
import model as modelImport
import torch

pick_device = 'cpu'
DEVICE = torch.device(pick_device)
model = modelImport.MyModel2().to(DEVICE)


In [8]:
for x in model.parameters():
    print(x)

Parameter containing:
tensor([[[[-0.2478,  0.2808,  0.0250],
          [ 0.2699,  0.2489, -0.3281],
          [ 0.2090,  0.0511, -0.0031]]],


        [[[-0.1557, -0.1154, -0.1337],
          [-0.3157, -0.2251, -0.1963],
          [ 0.3313,  0.0294,  0.1302]]],


        [[[-0.3309, -0.2853, -0.0039],
          [-0.2903, -0.1076, -0.1406],
          [-0.1644,  0.1732,  0.0014]]],


        [[[-0.3000,  0.2743,  0.1923],
          [ 0.2722, -0.3275, -0.1100],
          [-0.1309,  0.1634,  0.1880]]]], requires_grad=True)
Parameter containing:
tensor([-0.3185, -0.1076,  0.0320, -0.1569], requires_grad=True)
Parameter containing:
tensor([[ 0.0118,  0.0113,  0.0115,  ..., -0.0150, -0.0056,  0.0023],
        [ 0.0060, -0.0170, -0.0043,  ..., -0.0073,  0.0130,  0.0030],
        [ 0.0139,  0.0077, -0.0085,  ..., -0.0028,  0.0084, -0.0103],
        ...,
        [-0.0152,  0.0016,  0.0020,  ..., -0.0086,  0.0018,  0.0048],
        [-0.0171, -0.0050, -0.0137,  ..., -0.0141, -0.0001,  0.0113],
   

In [9]:
for x in model.modules() :
    print(x)

MyModel2(
  (conv1): Conv2d(1, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (relu): ReLU()
  (fc1): Linear(in_features=3136, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=10, bias=True)
)
Conv2d(1, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
ReLU()
Linear(in_features=3136, out_features=100, bias=True)
Linear(in_features=100, out_features=10, bias=True)


In [14]:
# print(model.modules())
# model_collection = [ x in model.modules()]
# print(model_collection)
entries = [entry for entry in model.modules()] ##need to ignore other files!?!?<<<<<<<<
print(entries)

[MyModel2(
  (conv1): Conv2d(1, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (relu): ReLU()
  (fc1): Linear(in_features=3136, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=10, bias=True)
), Conv2d(1, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)), ReLU(), Linear(in_features=3136, out_features=100, bias=True), Linear(in_features=100, out_features=10, bias=True)]
