In [1]:
import torch

In [10]:
device = 'cude' if torch.cuda.is_available() else "cpu"
device = 'mps'
tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device = device,requires_grad=True)

In [11]:
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='mps:0', requires_grad=True)


In [12]:
print(tensor.dtype)
print(tensor.device)
print(tensor.shape)
print(tensor.requires_grad)

torch.float32
mps:0
torch.Size([2, 3])
True


In [13]:
x = torch.empty(size = (3,3))

In [14]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [29]:
x=torch.rand((3,3))
print(x)
x=torch.ones(5,5)
print(x)
x=torch.arange(start =0,end=5,step =2)
print(x)
x = torch.linspace(start=0.1,end=1.,steps=10)
print(x)
x = torch.linspace(start=-4.,end=4.,steps=40)
print(x)
x=torch.arange(start =-4,end=4,step =0.3)
print(x)

tensor([[0.4998, 0.9992, 0.5657],
        [0.4048, 0.3162, 0.2646],
        [0.4323, 0.9148, 0.3618]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([0, 2, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([-4.0000, -3.7949, -3.5897, -3.3846, -3.1795, -2.9744, -2.7692, -2.5641,
        -2.3590, -2.1538, -1.9487, -1.7436, -1.5385, -1.3333, -1.1282, -0.9231,
        -0.7179, -0.5128, -0.3077, -0.1026,  0.1026,  0.3077,  0.5128,  0.7179,
         0.9231,  1.1282,  1.3333,  1.5385,  1.7436,  1.9487,  2.1538,  2.3590,
         2.5641,  2.7692,  2.9744,  3.1795,  3.3846,  3.5897,  3.7949,  4.0000])
tensor([-4.0000, -3.7000, -3.4000, -3.1000, -2.8000, -2.5000, -2.2000, -1.9000,
        -1.6000, -1.3000, -1.0000, -0.7000, -0.4000, -0.1000,  0.2000,  0.5000,
         0.8000,  1.1000,  1.4000,  1.7000,  2.0000,  2.3000,  2.6000,